name: CXXUhc
version: 1.0
author: CXXUHC
main: io.shine.cxxuhc.CXXUhc
commands:
    say:
        description: Say
    finish:
        description: Finish
    bug:
        description: Report BUG
    end:
        description: Ends the current UHC
    me:
        description: Me